version: "3.9"

services:
  chess-discord-bot:
    build: .
    container_name: chess-discord-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data           
      - ./logs:/app/logs
      - ./config.json:/app/config.json:ro
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
