ENV: &default_env
  DISCORD_TOKEN: $
  D_WEBHOOK_G: $
  D_WEBHOOK_T: $

# update:
#   env: *default_env
#   steps:
#     - cmd: echo "Start update"
#     - cmd: git pull
#     - cmd: docker-compose down
#     - cmd: docker-compose up --build -d
#       blocking: true

timeout: 800

branches: [main]

pipeline:
  notifications:
    on: [success, failure]
    thumbnail: https://github.com/user-attachments/assets/429bf6e8-5724-473e-a560-e9e06bbbc143
    channels:
      - service: discord
        url: https://discord.com/api/webhooks/1411403673028001989/WH1KIMmgxSNEF6kV_9-TQS1LadHASBLDJ5evPgMIo3Ko8NX40hcMom_InEo9YsNrRDmu
      - service: discord
        url: https://discord.com/api/webhooks/1411470873298469004/HfqOWWj1i90mSagePCJglL66RhNylWoAm2qH9jduPO8g_kAM9usvjeaT-hJJJOxCzz24
  jobs:
    pull:
      steps:
        - cmd: echo "Start update"
        - cmd: git pull
    
    down:
      steps:
        - cmd: docker-compose down
    
    deploy:
      needs: [down, pull]
      env: *default_env
      steps:
        - cmd: docker-compose up --build -d
